// Verbatim from the paper (arXiv:2609.30063). at = video seconds.
export const QUOTES: {at: number; text: string}[] = [
  // I. The big picture
  {at: 14, text: 'Advances in language modeling have been driven by scaling pretraining on ever more data. Yet, the training data is still largely curated on the model’s behalf.'},
  {
    at: 29,
    text: 'A more general approach to pretraining would let the model learn to generate the data most useful for its own improvement. This would provide an effectively unbounded source of training data, limited by compute rather than human knowledge.',
  },
  {at: 46, text: 'We test whether zero-shot performance on natural data improves predictably with self-play compute; this is a clean test of transfer since neither generator nor learner is trained on natural data.'},
  // II. How it works
  {
    at: 65,
    text: 'Starting from random initialization, two models learn in tandem: a generator proposes programs interpreted by a universal Turing machine, generating byte sequences, while a learner autoregressively predicts these byte sequences.',
  },
  {
    at: 79,
    text: 'We use a universal Turing machine to make the space of all synthetic training data as expressive as possible while imposing minimal domain-specific structure: any computable data-generating process can, in principle, be represented as a program.',
  },
  {
    at: 92,
    text: 'We use a Brainf*ck-like universal machine, … whose eight single-character instructions move the head between cells (<, >), increment or decrement the cell under it (+, -), loop ([, ]), and read or write bytes (, and .).',
  },
  {
    at: 104,
    text: 'However, the space of computable structure is enormous, and only a small subset of programs produce sequences that are useful for the learner. Moreover, whether a sequence is useful changes as the learner improves.',
  },
  {
    at: 116,
    text: 'Both are transformers with the same architecture, trained from random initialization; the generator is trained via reinforcement learning (RL) and the learner is trained via next-token prediction.',
  },
  // III. Training, and what it buys
  {at: 130, text: 'Concretely, we reward the generator for producing programs whose learner gradients align with the learner’s current learning trajectory.'},
  {
    at: 141,
    text: 'We expect that programs that are already mastered induce nearly zero gradients, while programs containing unrelated or unlearnable structure induce gradients that do not align with the learner’s parameter movement. Both receive little reward.',
  },
  {
    at: 153,
    text: 'Instead, high reward is assigned to programs that induce substantial learning, but only in directions congruent with the learner’s recent progress; this concentrates the generator on the frontier of the learner’s current capabilities.',
  },
  {
    at: 166,
    text: '…we designed a diverse set of benchmarks generated by different processes. Regardless of the provenance, they share the same interface, obtained by encoding them as byte sequences.',
  },
  {at: 181, text: 'Our results show that predictable improvements in next-token prediction on natural data can emerge even when no natural data is used for training.'},
];
